name: C++ Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        channels: bioconda,conda-forge,defaults
        channel-priority: true
        python-version: 3.7
        use-only-tar-bz2: true
        auto-activate-base: false
        activate-environment: test
    - name: Conda info
      run: |
        conda info
        conda list
    - name: Install BioPerl >=1.7.2
      run: conda install "perl-bioperl>=1.7.2" "gxx_linux-64 ==7.3.0" "perl-list-moreutils"
    - name: g++ version
      run: g++ --version
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: help
      run: b/aodp --help
    - name: version
      run: b/aodp --version
