name: C++ Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        auto-update-conda: true
        python-version: 3.8
    - name: Install BioPerl >=1.7.2
      run: conda install -c bioconda "perl-bioperl>=1.7.2"
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: help
      run: b/aodp --help
    - name: version
      run: b/aodp --version
